from search.breadth_first_search import breadth_first_search
from search.depth_first_search import depth_first_search
from search.a_star_search import a_star_search
from search.iterative_deepening_search import iterative_deepening_search
from search.machine_learning_search import machine_learning_search
from search.machine_learning_search_2 import machine_learning_search_2
from search.machine_learning_search_2_imported import machine_learning_search_2_imported
from search.best_first_search import best_first_search